import { requireAuth } from '../../guards.js';
import { mountShell } from '../../app.js';
import { createToast } from '../../components/toast.js';
import { listRecords, saveRecord } from '../../firebase/firestore.js';

const collections = ['customers','vehicles','quotes','serviceOrders','products','suppliers','services','payments','reminders','appointments'];
const profile = await requireAuth({ role:'admin' });
const page = mountShell(profile || { name:'Configuração pendente', role:'admin' }, { title:'Backup', active:'administracao' });
page.innerHTML = `<section class="page-heading"><div><h1>Backup e restauração</h1><p>Baixe uma cópia dos dados ou restaure um arquivo do sistema.</p></div></section><section class="card"><div class="card-body form-grid"><div class="field full"><strong>Backup completo</strong><p>Inclui clientes, veículos, orçamentos, OS, estoque, fornecedores, serviços, financeiro, lembretes e agenda.</p><button class="btn btn-primary" type="button" id="download-backup">Baixar backup</button></div><div class="field full"><label>Restaurar backup JSON</label><input class="input" type="file" id="restore-file" accept="application/json,.json"><small>A restauração adiciona os registros à empresa atual e não remove dados existentes.</small></div><div class="field full"><button class="btn" type="button" id="restore-backup">Restaurar arquivo</button></div></div></section>`;
const clean = value => JSON.parse(JSON.stringify(value, (_, item) => typeof item?.toDate === 'function' ? item.toDate().toISOString() : item));
const download = (name, text) => { const link=document.createElement('a'); link.href=URL.createObjectURL(new Blob([text],{type:'application/json'})); link.download=name; link.click(); URL.revokeObjectURL(link.href); };
if (profile) {
  page.querySelector('#download-backup').addEventListener('click', async event => { event.currentTarget.disabled=true; try { const entries=await Promise.all(collections.map(async name=>[name,(await listRecords(name,profile.companyId,{pageSize:1000})).records.map(clean)])); download(`backup-garagem-auto-car-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),data:Object.fromEntries(entries)},null,2));createToast('Backup baixado com sucesso.'); } catch(error){console.error(error);createToast('Não foi possível gerar o backup.','error');} finally{event.currentTarget.disabled=false;} });
  page.querySelector('#restore-backup').addEventListener('click',async event=>{const file=page.querySelector('#restore-file').files[0];if(!file)return createToast('Selecione um arquivo de backup.','error');event.currentTarget.disabled=true;try{const backup=JSON.parse(await file.text());if(!backup?.data||typeof backup.data!=='object')throw new Error('Arquivo inválido');let count=0;for(const name of collections)for(const item of Array.isArray(backup.data[name])?backup.data[name]:[]){const {id,companyId,createdAt,updatedAt,deletedAt,...data}=item;await saveRecord(name,profile.companyId,data);count+=1;}createToast(`${count} registro(s) restaurado(s).`);}catch(error){console.error(error);createToast('Arquivo inválido ou não foi possível restaurar.','error');}finally{event.currentTarget.disabled=false;}});
}
