import { requireAuth } from '../../guards.js';
import { mountShell } from '../../app.js';
import { createModal, createConfirmDialog } from '../../components/modal.js';
import { createToast } from '../../components/toast.js';
import { getIcon } from '../../components/icons.js';
import { listRecords, saveRecord, softDelete } from '../../firebase/firestore.js';

const profile = await requireAuth({role:'admin'});
const page = mountShell(profile||{name:'Configuração pendente',role:'admin'},{title:'Agenda',active:'agenda'});
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let appointments=[];
let visibleMonth=new Date(); visibleMonth.setDate(1);

page.classList.add('agenda-page');
page.innerHTML=`<div class="setup-banner">Configure o Firebase para carregar a agenda.</div><section class="page-heading page-hero"><span class="page-hero-icon">${getIcon('calendar',30)}</span><div><h1>Agenda</h1><p>Visualize compromissos, agendamentos e entregas.</p></div><button class="btn btn-primary" id="new-appointment">${getIcon('plus')} Novo agendamento</button></section><section class="toolbar agenda-toolbar"><select class="select" id="month-filter"></select><select class="select" id="type-filter"><option value="">Todos os tipos</option><option>Serviço</option><option>Retorno</option><option>Entrega</option></select><select class="select" id="status-filter"><option value="">Todos os status</option><option>Agendado</option><option>Confirmado</option><option>Em atendimento</option><option>Concluído</option><option>Cancelado</option></select><label class="search">${getIcon('search')}<input class="input" id="agenda-search" placeholder="Buscar na agenda..."></label></section><section class="agenda-layout"><article class="card agenda-calendar-card"><header class="agenda-calendar-header"><div><button class="btn btn-icon" id="prev-month">‹</button><button class="btn btn-icon" id="next-month">›</button></div><h2 id="calendar-title"></h2><div class="agenda-view-switch"><button class="active">Mês</button><button>Semana</button><button>Dia</button></div></header><div class="agenda-weekdays">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=>`<span>${day}</span>`).join('')}</div><div class="agenda-calendar" id="agenda-calendar"></div></article><aside class="agenda-side"><article class="card agenda-panel"><header class="reference-card-header"><span class="module-list-icon">${getIcon('calendar',20)}</span><div><h2>Compromissos de hoje</h2><p id="today-label"></p></div><b id="today-count">0</b></header><div id="today-list"></div></article><article class="card agenda-panel"><header class="reference-card-header"><span class="module-list-icon">${getIcon('calendar',20)}</span><div><h2>Próximos compromissos</h2><p>Próximos agendamentos</p></div><b id="upcoming-count">0</b></header><div id="upcoming-list"></div></article></aside></section>`;

function appointmentForm(record={}){const form=document.createElement('form');form.className='form-grid';form.innerHTML=`<div class="field"><label>Cliente</label><input class="input" name="customerName" value="${escapeHtml(record.customerName||'')}" required></div><div class="field"><label>Veículo</label><input class="input" name="vehicle" value="${escapeHtml(record.vehicle||'')}"></div><div class="field"><label>Placa</label><input class="input" name="plate" value="${escapeHtml(record.plate||'')}"></div><div class="field"><label>Serviço</label><input class="input" name="service" value="${escapeHtml(record.service||'')}" required></div><div class="field"><label>Data</label><input class="input" name="date" type="date" value="${escapeHtml(record.date||'')}" required></div><div class="field"><label>Horário</label><input class="input" name="time" type="time" value="${escapeHtml(record.time||'')}" required></div><div class="field"><label>Responsável</label><input class="input" name="responsible" value="${escapeHtml(record.responsible||'')}"></div><div class="field"><label>Status</label><select class="select" name="status">${['Agendado','Confirmado','Em atendimento','Concluído','Cancelado'].map(status=>`<option ${record.status===status?'selected':''}>${status}</option>`).join('')}</select></div><div class="field full"><label>Observações</label><textarea class="textarea" name="notes">${escapeHtml(record.notes||'')}</textarea></div>`;return form;}
function openForm(record=null){const form=appointmentForm(record||{});createModal({title:record?'Editar agendamento':'Novo agendamento',content:form,confirmText:record?'Salvar':'Cadastrar',onConfirm:async()=>{if(!form.reportValidity())return false;const data=Object.fromEntries(new FormData(form));await saveRecord('appointments',profile.companyId,data,record?.id);createToast('Agendamento salvo com sucesso.');await load();}});}
function itemHtml(item){return `<article class="agenda-item"><time>${escapeHtml(item.time||'--:--')}</time><span></span><div><strong>${escapeHtml(item.service||'Compromisso')}</strong><p>${escapeHtml(item.vehicle||item.customerName||'')}</p></div><span class="badge">${escapeHtml(item.status||'Agendado')}</span><details class="row-menu"><summary class="btn btn-icon">${getIcon('more',16)}</summary><div><button data-action="edit" data-id="${item.id}">${getIcon('edit',14)} Editar</button><button class="danger" data-action="delete" data-id="${item.id}">${getIcon('trash',14)} Excluir</button></div></details></article>`;}
function render(){const year=visibleMonth.getFullYear(),month=visibleMonth.getMonth();page.querySelector('#calendar-title').textContent=visibleMonth.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});const firstDay=new Date(year,month,1).getDay();const totalDays=new Date(year,month+1,0).getDate();const previousTotal=new Date(year,month,0).getDate();const cells=[];for(let index=0;index<42;index+=1){let day=index-firstDay+1,cellMonth=month,muted=false;if(day<1){day=previousTotal+day;cellMonth=month-1;muted=true;}else if(day>totalDays){day-=totalDays;cellMonth=month+1;muted=true;}const date=new Date(year,cellMonth,day);const key=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(day).padStart(2,'0')].join('-');const events=appointments.filter(item=>item.date===key).slice(0,2);cells.push(`<div class="agenda-day ${muted?'muted':''} ${key===new Date().toISOString().slice(0,10)?'today':''}"><b>${day}</b>${events.map(item=>`<button data-id="${item.id}"><span></span>${escapeHtml(item.time||'')} ${escapeHtml(item.service||item.customerName||'')}</button>`).join('')}</div>`);}page.querySelector('#agenda-calendar').innerHTML=cells.join('');const today=new Date().toISOString().slice(0,10);const todays=appointments.filter(item=>item.date===today);const upcoming=appointments.filter(item=>item.date>today).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).slice(0,6);page.querySelector('#today-label').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});page.querySelector('#today-count').textContent=todays.length;page.querySelector('#upcoming-count').textContent=upcoming.length;page.querySelector('#today-list').innerHTML=todays.map(itemHtml).join('')||'<div class="agenda-panel-empty">Nenhum compromisso hoje.</div>';page.querySelector('#upcoming-list').innerHTML=upcoming.map(itemHtml).join('')||'<div class="agenda-panel-empty">Nenhum próximo compromisso.</div>';}
async function load(){appointments=(await listRecords('appointments',profile.companyId,{pageSize:1000})).records;render();}
page.querySelector('#new-appointment').addEventListener('click',()=>openForm());page.querySelector('#prev-month').addEventListener('click',()=>{visibleMonth.setMonth(visibleMonth.getMonth()-1);render();});page.querySelector('#next-month').addEventListener('click',()=>{visibleMonth.setMonth(visibleMonth.getMonth()+1);render();});page.querySelectorAll('#today-list,#upcoming-list').forEach(container=>container.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const item=appointments.find(entry=>entry.id===button.dataset.id);if(button.dataset.action==='edit')openForm(item);if(button.dataset.action==='delete')createConfirmDialog('Excluir este agendamento?',async()=>{await softDelete('appointments',item.id,profile.uid);await load();});}));
page.querySelector('#month-filter').innerHTML=`<option>${visibleMonth.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</option>`;
page.querySelector('#agenda-search').addEventListener('input',render);
page.querySelector('#status-filter').addEventListener('change',render);
if(profile)await load();
