import * as XLSX from 'https://cdn.jsdelivr.net/npm/xlsx@0.18.5/+esm';
import { requireAuth } from '../../guards.js';
import { mountShell } from '../../app.js';
import { saveRecord } from '../../firebase/firestore.js';
import { createToast } from '../../components/toast.js';

const profile=await requireAuth({role:'admin'});const page=mountShell(profile||{name:'Configuração pendente',role:'admin'},{title:'Importar dados',active:'administracao'});
page.innerHTML=`<section class="page-heading"><div><h1>Importar dados</h1><p>Importe CSV, XLSX ou JSON com pré-visualização e mapeamento.</p></div></section><section class="card"><div class="card-body form-grid"><div class="field"><label>Tipo de dado</label><select id="collection" class="select"><option value="customers">Clientes</option><option value="vehicles">Veículos</option><option value="products">Produtos</option><option value="services">Serviços</option><option value="suppliers">Fornecedores</option></select></div><div class="field"><label>Arquivo</label><input id="file" class="input" type="file" accept=".csv,.xlsx,.xls,.json"></div><div class="field full"><button class="btn btn-primary" id="analyze" type="button">Analisar arquivo</button></div></div></section><section class="card" style="margin-top:18px"><header class="card-header"><h2>Pré-visualização</h2><button class="btn btn-primary" id="import" disabled>Importar registros válidos</button></header><div id="preview" class="card-body"><div class="empty">Selecione um arquivo para começar.</div></div></section>`;
let rows=[];
page.querySelector('#analyze').addEventListener('click',async()=>{const file=page.querySelector('#file').files[0];if(!file)return;const buffer=await file.arrayBuffer();if(file.name.endsWith('.json'))rows=JSON.parse(new TextDecoder().decode(buffer));else{const workbook=XLSX.read(buffer);rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});}if(!Array.isArray(rows))rows=[];const duplicates=new Set();const seen=new Set();rows.forEach((row,index)=>{const key=String(row.cpf||row.cnpj||row.document||row.placa||row.plate||row.telefone||row.phone||'').replace(/\D/g,'');if(key&&seen.has(key))duplicates.add(index);seen.add(key);});const keys=[...new Set(rows.flatMap(Object.keys))];page.querySelector('#preview').innerHTML=rows.length?`<p><strong>${rows.length}</strong> registro(s), <strong>${duplicates.size}</strong> possível(is) duplicado(s).</p><div class="table-wrap"><table class="table"><thead><tr>${keys.slice(0,6).map(key=>`<th>${key}</th>`).join('')}<th>Validação</th></tr></thead><tbody>${rows.slice(0,50).map((row,index)=>`<tr>${keys.slice(0,6).map(key=>`<td>${row[key]??''}</td>`).join('')}<td><span class="badge ${duplicates.has(index)?'badge-warning':'badge-success'}">${duplicates.has(index)?'Possível duplicado':'Válido'}</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum registro identificado.</div>';page.querySelector('#import').disabled=!rows.length;});
page.querySelector('#import').addEventListener('click',async event=>{event.currentTarget.disabled=true;let imported=0;for(const row of rows){const normalized=Object.fromEntries(Object.entries(row).map(([key,value])=>[key.trim().toLowerCase().replaceAll(' ','_'),value]));await saveRecord(page.querySelector('#collection').value,profile.companyId,normalized);imported+=1;}createToast(`${imported} registro(s) importado(s).`);event.currentTarget.disabled=false;});
