import * as XLSX from 'https://cdn.jsdelivr.net/npm/xlsx@0.18.5/+esm';
import { requireAuth } from '../../guards.js';
import { mountShell } from '../../app.js';
import { saveRecord } from '../../firebase/firestore.js';
import { createToast } from '../../components/toast.js';
import { adminBackButton } from '../../components/admin-back.js';

const profile = await requireAuth({ role:'admin' });
const page = mountShell(profile || {name:'Configuração pendente',role:'admin'}, {title:'Importar dados',active:'administracao'});
page.innerHTML = `<section class="page-heading"><div><h1>Importar dados</h1><p>Importe CSV, XLSX ou JSON com pré-visualização e mapeamento.</p></div>${adminBackButton()}</section><section class="card"><div class="card-body form-grid"><div class="field"><label>Tipo de dado</label><select id="collection" class="select"><option value="customers">Clientes</option><option value="vehicles">Veículos</option><option value="products">Produtos</option><option value="services">Serviços</option><option value="suppliers">Fornecedores</option></select></div><div class="field"><label>Arquivo</label><input id="file" class="input" type="file" accept=".csv,.xlsx,.xls,.json"></div><div class="field full"><button class="btn btn-primary" id="analyze" type="button">Analisar arquivo</button></div></div></section><section class="card" style="margin-top:18px"><header class="card-header"><h2>Pré-visualização</h2><button class="btn btn-primary" id="import" disabled>Importar registros válidos</button></header><div id="preview" class="card-body"><div class="empty">Selecione um arquivo para começar.</div></div></section>`;
let rows=[];
page.querySelector('#analyze').addEventListener('click',async()=>{const file=page.querySelector('#file').files[0];if(!file)return;const buffer=await file.arrayBuffer();if(file.name.endsWith('.json')){const parsed=JSON.parse(new TextDecoder().decode(buffer));rows=Array.isArray(parsed)?parsed:parsed.records||[];}else{const workbook=XLSX.read(buffer);rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});}if(!Array.isArray(rows))rows=[];const keys=[...new Set(rows.flatMap(Object.keys))];page.querySelector('#preview').innerHTML=rows.length?`<p><strong>${rows.length}</strong> registro(s) identificados.</p><div class="table-wrap"><table class="table"><thead><tr>${keys.slice(0,6).map(key=>`<th>${key}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(row=>`<tr>${keys.slice(0,6).map(key=>`<td>${row[key]??''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum registro identificado.</div>';page.querySelector('#import').disabled=!rows.length;});
page.querySelector('#import').addEventListener('click',async event=>{event.currentTarget.disabled=true;let imported=0;for(const row of rows){const normalized=Object.fromEntries(Object.entries(row).map(([key,value])=>[key.trim().toLowerCase().replaceAll(' ','_'),value]));await saveRecord(page.querySelector('#collection').value,profile.companyId,normalized);imported+=1;}createToast(`${imported} registro(s) importado(s).`);event.currentTarget.disabled=false;});
