import { createCrudPage } from '../crud-page.js';
import { maskPlate } from '../../utils/masks.js';
createCrudPage({
  title:'Veículos',active:'veiculos',collection:'vehicles',singular:'veículo',titleKey:'plate',newLabel:'Novo veículo',roles:['admin','atendente'],icon:'car',subtitle:'Acompanhe todos os veículos cadastrados e em atendimento.',searchPlaceholder:'Pesquisar por placa, modelo, cliente...',searchKeys:['plate','model','brand','ownerName'],
  metrics:records=>[{icon:'car',label:'Total de veículos',value:records.length,tone:'orange'},{icon:'wrench',label:'Em atendimento',value:records.filter(item=>['Em atendimento','Em execução'].includes(item.status)).length,tone:'orange'},{icon:'check',label:'Concluídos no mês',value:records.filter(item=>['Concluído','Entregue'].includes(item.status)).length,tone:'green'},{icon:'clock',label:'Aguardando entrega',value:records.filter(item=>String(item.status||'').includes('Aguardando')).length,tone:'orange'}],
  columns:[{key:'plate',label:'Placa'},{key:'model',label:'Modelo',render:(value,record)=>`<div class="vehicle-cell">${record.imageData?`<img src="${record.imageData}" alt="">`:'<span>—</span>'}<div><strong>${record.brand||''} ${value||''}</strong><small>${record.modelYear||record.manufactureYear||''} ${record.version||''}</small></div></div>`},{key:'ownerName',label:'Cliente'},{key:'status',label:'Status',render:value=>`<span class="badge">${value||'Cadastrado'}</span>`},{key:'createdAt',label:'Entrada',render:value=>value?.toDate?value.toDate().toLocaleDateString('pt-BR'):'—'}],
  fields:[{key:'ownerName',label:'Proprietário',required:true},{key:'customerId',label:'Cliente cadastrado',reference:{collection:'customers',label:item=>item.name || item.email || 'Cliente',copy:{ownerName:'name'}}},{key:'plate',label:'Placa',required:true},{key:'brand',label:'Marca',required:true},{key:'model',label:'Modelo',required:true},{key:'version',label:'Versão'},{key:'manufactureYear',label:'Ano fabricação',type:'number'},{key:'modelYear',label:'Ano modelo',type:'number'},{key:'color',label:'Cor'},{key:'fuel',label:'Combustível'},{key:'transmission',label:'Câmbio'},{key:'mileage',label:'Quilometragem',type:'number'},{key:'renavam',label:'RENAVAM'},{key:'chassis',label:'Chassi'},{key:'engine',label:'Motor'},{key:'imageData',label:'Foto do veículo',type:'image',full:true,hiddenInDetails:true},{key:'notes',label:'Observações',type:'textarea',full:true}],
  normalize:data=>({...data,plate:maskPlate(data.plate),mileage:Number(data.mileage)||0,manufactureYear:Number(data.manufactureYear)||null,modelYear:Number(data.modelYear)||null})
});
